### ISSUE TITLE
Your Newest update to the mods does this crash.

### ISSUE THREAD

**Issue by SirTwsted** [jimmyjon711/FactorioExtended-Plus-Transport#12]
.
. When your mod was updated to its most recent update within my game,
It created a crash after factorio v17.9 was restarted after your mods got updated.
specifically with the "Transport" mod.
https://imgur.com/a/EkM3rrR

**Comment by TheMak** [comment]
Can confirm, have the same issue.  I am using the previous version (2.1) and no issues.

**Comment by jimmyjon711** [comment]
@SirTwsted @TheMak Can one of you send/upload your save so I can see whats going on?
I think I know what the issue but I would like to verify my fix with one of your saves, since I do not get this error.

**Comment by jimmyjon711** [comment]
Wait i'm not sure why i'm asking for your save because it only happens when you load the game. Doh!
hmmmmm, I wonder why i'm not having this issue.
Could you guys list off your other mods and version of those mods, maybe something else is interfering with them.

**Comment by jimmyjon711** [comment]
So it looks like bob updated his logistics mod to put fast_replacement_group to "pipe" for all his pipe. Please update all your mods and let me know if you still have an issue

**Comment by SirTwsted** [comment]
problem still happens as of 03-12-2019  at 7:45-EST/EDT
I updated ALL of Bobs mods to the latest versions.  The problem is on your Transport mod.
just wanted to update you on the outcome of today.  Still waiting on a fix from your end.  :)

**Comment by jimmyjon711** [comment]
@SirTwsted can you list all your other mods so that I can load them on my end, I am not getting this error currently

**Comment by SirTwsted** [comment]
check forums as I posted it there.
sorry for the late response, I have a 9-to-5.

**Comment by Seyeght** [comment]
I am also getting this issue, this happens before I can load a save, would be happy to assist in providing whatever is needed to locate the issue.

**Comment by Seyeght** [comment]
Here is the mods folder that I am trying to run, and if I enable FactorioExtended Plus Transport I get an identical crash report on game launch as posted in the initial screenshot.
https://drive.google.com/file/d/1-m_SO3HwZBAKl_Dj9shppm1kydfZw1h5/view?usp=sharing
