### ISSUE TITLE
0.17.23

### ISSUE THREAD

**Issue by cole4114** [jimmyjon711/FactorioExtended-Plus-Transport#15]
"Error in assignID, recipe with name 'purple-loader' does not exist"

**Comment by jimmyjon711** [comment]
Thanks for the report, but I do not get this message. Does the message occur when loading the game? Do you have other mods that could be causing this error?

**Comment by cole4114** [comment]
Mods to be disabled:
FactorioExtended-Plus-Transport
LoaderRedux
deadlock-integrations

**Comment by cole4114** [comment]
[factorio-current.log](https://github.com/jimmyjon711/FactorioExtended-Plus-Transport/files/3027004/factorio-current.log)

**Comment by jimmyjon711** [comment]
purple-loader is being referenced in the LoaderRedux mod, please file a bug report with that mod owner

Edit: it looks like you already have
