### ISSUE TITLE
having trouble loading the mod 

### ISSUE THREAD

**Issue by metalfan1018** [jimmyjon711/FactorioExtended-Plus-Transport#17]
im trying to play factorio extended and i keep getting this error message
https://cdn.discordapp.com/attachments/521756349051174932/581117247590760478/unknown.png
https://cdn.discordapp.com/attachments/477170780174549002/581124795081424899/unknown.png
im trying to play factorio extended with lovely_santas more science mod and its having compatability issues can you please fix this?

**Comment by jimmyjon711** [comment]
This issue has been fixed and new version has been updated to the mod portal. Please let me know if you encounter any more issues with this problem
