### ISSUE TITLE
Migration error, when you do not have fluid-handling-2

### ISSUE THREAD

**Issue by maystery** [jimmyjon711/FactorioExtended-Plus-Transport#18]
Hello!

I got the following error when I've tried to install this modpack: 

```
Error while applying migration: FactorioExtended Plus-Transport: FactorioExtended-Plus-Transport_0.1.2.lua

...t__/migrations/FactorioExtended-Plus-Transport_0.1.2.lua:5: attempt to index field 'fluid-handling-2' (a nil value)
stack traceback:
	...t__/migrations/FactorioExtended-Plus-Transport_0.1.2.lua:5: in main chunk
```

The save was a lightly modded game created in 17.x .

**Comment by jimmyjon711** [comment]
You get this error loading a game or doing a tutorial?

**Comment by maystery** [comment]
I got this error, during loading. I have a save file and just enabled the mod on it.

**Comment by jimmyjon711** [comment]
you have other mods, I only get it when going to a tutorial. I can't replicate the error by just loading a game though

**Comment by jimmyjon711** [comment]
An update has been uploaded to the mod portal, please let me know if you still have problems

**Comment by maystery** [comment]
Now it works. Thanks for the fix.
