### ISSUE TITLE
Error loading with Factorio 0.17.67+

### ISSUE THREAD

**Issue by dfinton** [jimmyjon711/FactorioExtended-Plus-Transport#20]
Since the update for Factorio 0.17.67 and higher, the Transport mod has been reporting this fatal error. Factorio won't continue loading until I disable the mod.
```
Error loading mods

Failed to load mods: Error while running setup for entity prototype "pump" (pump): next_upgrade target (pump-mk2) must have same bounding box.
```

**Comment by jimmyjon711** [comment]
Do you have other mods installed, if so what are they?

**Comment by dfinton** [comment]
@jimmyjon711 - Issue's been resolved (thanks!), but to answer your question:

- Alien Biomes (High_Res)
- Bob's Enemies
- Bullet Trails
- Disco Science
- Even Distribution
- FNEI
- Longer Days and Nights
- Mushroom Cloud
- Robot Attrition
