### ISSUE TITLE
Mod compatibility request

### ISSUE THREAD

**Issue by DeadlyKitten37** [jimmyjon711/FactorioExtended-Plus-Transport#23]
Can you please add compatibility with the mod LoaderRedux https://mods.factorio.com/mod/LoaderRedux

**Comment by billbo99** [comment]
Ok started to do some Investigations.

**Comment by billbo99** [comment]
I have created a bridging mod below to support LoaderRedux & FE+
   https://mods.factorio.com/mod/LoaderReduxForFactorioExtendedPlus

Think it was a cleaner approach and this has been done before for deadlock loaders.

**Comment by DeadlyKitten37** [comment]
Thx
