### ISSUE TITLE
18.19 breaks this mod

### ISSUE THREAD

**Issue by dnulho** [jimmyjon711/FactorioExtended-Plus-Transport#31]
A change from 18.18 to 18.19 breaks this mod.

I am getting the attached error on launch.
![image](https://user-images.githubusercontent.com/5905416/79753438-eb97c280-82e3-11ea-9ca7-66ae26e86255.png)

If you want additional info, I will try to provide it.

**Comment by eagle00789** [comment]
#32 thiss will fix this issue quick and dirty....
