### ISSUE TITLE
FactorioExtended Plus transport

### ISSUE THREAD

**Issue by LazyTurtle61** [jimmyjon711/FactorioExtended-Plus-Transport#33]
![Aantekening 2020-04-21 163609](https://user-images.githubusercontent.com/64089224/79879796-744f5500-83ef-11ea-9b22-cb73d09dd437.png)
i Got an error with factorio extended plus transport mod 
see image ^^

**Comment by LazyTurtle61** [comment]
i tried it without space ex still the problem

**Comment by jimmyjon711** [comment]
If you are running factorio version 0.18.19 then please update to transport version 0.4.4, this should be fixed in that version

**Comment by LazyTurtle61** [comment]
it doesnt let me update it in factorio i tried redownloading it alrdy

**Comment by LazyTurtle61** [comment]
nvm had to go to 0.18.19
