### ISSUE TITLE
Icons in deconstruction/upgrade-planner is the same as the base game ones

### ISSUE THREAD

**Issue by spaam** [jimmyjon711/FactorioExtended-Plus-Transport#42]
pipes-mk2, underground-mk2, pump-mk2, offshore-pump-mk2, cargo-wagon-mk2,cargo-wagon-mk3, fluid-wagon-mk2. fluid-wagon-mk3, locomotive-mk2 and locomotive-mk3

**Comment by Necril** [comment]
For me they don't even show up in the upgrade planner. The old planners from before 1.0 had icons in them but they didn't work.

**Comment by billbo99** [comment]
Train parts (wagons / locomotives) can not be upgraded,  that's a factorio game limitation.

**Comment by Necril** [comment]
ok but what about the pipes and the pumps?

**Comment by billbo99** [comment]
#45 will fix that when merged by Jimmy
