### ISSUE TITLE
error loading mods

### ISSUE THREAD

**Issue by walzu1** [jimmyjon711/FactorioExtended-Plus-Transport#46]
since new update i cant load the mod it gives this error message :
![image](https://user-images.githubusercontent.com/74872871/99910937-62b98d00-2cf1-11eb-8af0-6898b9813c94.png)

**Comment by kentperrier** [comment]
I have the same issue, along with Pump Anywhere and PressurizedBarrels

![image](https://user-images.githubusercontent.com/8590678/99917948-5f1a0c00-2cd9-11eb-841c-d0541d7dc72e.png)

**Comment by walzu1** [comment]
so its a problem with a the pumps?

**Comment by billbo99** [comment]
its been fixed
