### ISSUE TITLE
Bugs with rapid belts

### ISSUE THREAD

**Issue by pgking** [jimmyjon711/FactorioExtended-Plus-Transport#8]
Game crashes when setting recipes for both rapid belt MK1 and 2 on assembler 5.
Works fine for Assemblers 4 though so i'll be using those for now.
[factorio-current.log](https://github.com/jimmyjon711/FactorioExtended-Plus-Core/files/2921873/factorio-current.log)

There is a visual bug for rapid belts MK2 going down (even though they work fine).
I don't know how to share a gif here so here is the proof link, apologies.
https://gyazo.com/1bd3c609684462e72cdf0fb3e7e305eb

Thanks for everything !

**Comment by jimmyjon711** [comment]
These issues should now be fixed in 0.2.1 release, please let me know if you still have problems with the assembler 5 issue. After I updated the graphics and properties the game didn't crash for me.
